### STAGE 1: Build ###

FROM node:10.18.0-alpine AS build

# install git
RUN apk add git

# default directory opened by VSCode via Remote - Containers extension
WORKDIR /usr/src/app/src

# copy everything (including .git folder) to /usr/src/app/src
COPY . .

# cd to frontend
WORKDIR /usr/src/app/src/frontend

# copy package.json & package-lock.json
# COPY frontend/package.json .

RUN npm cache clean --force
RUN npm install

# copy contents of current dir to /usr/src/app/src/frontend
# COPY . .

# set color prompt for easier use
RUN export PS1="\e[0;36m \w \$ \e[m"

EXPOSE 8080

# call start script from package.json
CMD ["npm","start"]