### STAGE 1: Build ###

FROM node:10.18.0-alpine AS build
WORKDIR /usr/src/app

# copy package.json & package-lock.json
COPY package.json ./

RUN npm cache clean --force
RUN npm install

# copy contents of current dir to /usr/src/app
COPY . .

EXPOSE 8080

# call start script from package.json
CMD ["npm","start"]