version: '3' # specify docker-compose version

# Define the services/ containers to be run
services:
    angular: # name of the first service
        build:
            context: . # dev: .  prod: ./frontend   # because dev needs everything (including .git folder) to use as env.
            dockerfile: frontend/Dockerfile.dev # dev: Dockerfile.dev  prod: Dockerfile.prod
        ports:
            - "8080:8080" # dev: 8080:8080  prod: 80:80
            #- "443:443" # prod only
        # volumes: # prod only
            #-  "./frontend/letsencrypt:/etc/letsencrypt" # prod only: mount certificate data directory
        
        
    express: # name of the second service
        build: ./backend # build using Dockerfile in this directory
        ports:
            - "8081:8081"
        depends_on:
            - database # link this service to the database service
        
    database: # name of the third service
        image: mongo # instead of using a dockerfile (build cmd), I can just use a raw image since no further setup is required
        ports:
            - "27017:27017"